package gui;

import models.Graph;
import models.Noeud;

/**
 *
 * @author Elliot
 */
public class VoisinageNoeudForm extends javax.swing.JDialog {


    /**
     * Creates new form VoisinageNoeudForm
     */
    public VoisinageNoeudForm(java.awt.Frame parent, boolean modal,String title, Graph graph, Noeud source) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                dispose();
            }
        });
        graphDisplayPane.setSelectsNumberAbility(1);
        //graphDisplayPane.setSelectAbility(false);
        graphDisplayPane.setGraph(graph);
        graphDisplayPane.selectNoeud(source);
        this.setTitle(title);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphDisplayPane = new gui.GraphDisplayPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout graphDisplayPaneLayout = new javax.swing.GroupLayout(graphDisplayPane);
        graphDisplayPane.setLayout(graphDisplayPaneLayout);
        graphDisplayPaneLayout.setHorizontalGroup(
            graphDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );
        graphDisplayPaneLayout.setVerticalGroup(
            graphDisplayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        getContentPane().add(graphDisplayPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.GraphDisplayPane graphDisplayPane;
    // End of variables declaration//GEN-END:variables
}
